export const REQUEST_LOAD_CART = 'CART/REQUEST_LOAD_CART';
export const REQUEST_ADD_CART = 'CART/REQUEST_ADD_CART';
export const REQUEST_REMOVE_CART = 'CART/REQUEST_REMOVE_CART';
export const REQUEST_EMPTY_CART = 'CART/REQUEST_EMPTY_CART';

export const REQUEST_ASC_QUANTITY = 'CART/REQUEST_ASC_QUANTITY';
export const REQUEST_DESC_QUANTITY = 'CART/REQUEST_DESC_QUANTITY';