export const REQUEST_FETCH = 'LEFLAIR/REQUEST_FETCHL';
export const REQUEST_FETCH_SUCCESS = 'LEFLAIR/REQUEST_FETCHL_SUCCESS';
export const REQUEST_FETCH_FAIL = 'LEFLAIR/REQUEST_FETCHL_FAIL';

export const REQUEST_FETCH_BY_ID = 'LEFLAIR/REQUEST_FETCH_BY_ID';
export const REQUEST_FETCH_BY_ID_SUCCESS = 'LEFLAIR/REQUEST_FETCH_BY_ID_SUCCESS';
export const REQUEST_FETCH_BY_ID_FAIL = 'LEFLAIR/REQUEST_FETCH_BY_ID_FAIL';